#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Contao\Monorepo\Command\SplitCommand;

$application = new Application();

$application->add(new SplitCommand());

$application->run();
