name: CI

on:
    pull_request: ~
    push:
        branches:
            - main
        tags:
            - '*'
    schedule:
        - cron: 0 13 * * MON,THU

jobs:
    coverage:
        name: Coverage
        runs-on: ubuntu-latest
        if: github.event_name != 'schedule'
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, pcre, pdo, zlib
                  coverage: pcov

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: composer install --no-interaction --no-progress

            - name: Generate the coverage report
              run: php -d pcov.enabled=1 vendor/bin/phpunit --coverage-clover=clover.xml

            - name: Upload the coverage report
              uses: codecov/codecov-action@v3
              with:
                  files: ./clover.xml
                  fail_ci_if_error: true
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    coding-style:
        name: Coding Style
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, pcre, pdo, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: composer install --no-interaction --no-progress

            - name: Run Rector
              run: vendor/bin/rector --dry-run --no-progress-bar

            - name: Run ECS
              run: vendor/bin/ecs check --no-progress-bar

            - name: Run PHPStan
              run: vendor/bin/phpstan analyse --no-progress

    tests:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        if: github.event_name != 'push'
        strategy:
            fail-fast: false
            matrix:
                php: [8.1, 8.2, 8.3]
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: composer install --no-interaction --no-progress

            - name: Run the unit tests
              run: vendor/bin/phpunit

    nightly:
        name: PHP 8.4
        runs-on: ubuntu-latest
        if: github.event_name != 'push'
        continue-on-error: true
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: composer install --ignore-platform-req=php+ --no-interaction --no-progress

            - name: Run the unit tests
              run: vendor/bin/phpunit

    prefer-lowest:
        name: Prefer Lowest
        runs-on: ubuntu-latest
        if: github.event_name != 'push'
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: composer update --prefer-lowest --prefer-stable --no-interaction --no-progress

            - name: Run the unit tests
              run: vendor/bin/phpunit
