name: CI

on:
    pull_request: ~
    push:
        branches:
            - main
        tags:
            - '*'
    schedule:
        - cron: 0 13 * * MON,THU

jobs:
    coding-style:
        name: Coding Style
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, pcre, pdo, zlib
                  tools: prestissimo, flex
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: composer install --no-interaction --no-suggest

            - name: Run Rector
              run: vendor/bin/rector --dry-run --no-progress-bar --ansi

            - name: Run ECS
              run: vendor/bin/ecs check --no-progress-bar --ansi

            - name: Run PHPStan
              run: vendor/bin/phpstan analyse --no-progress

    tests:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        if: github.event_name != 'push'
        strategy:
            fail-fast: false
            matrix:
                php: [8.1, 8.2, 8.3]
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, pcre, pdo_mysql, zlib
                  tools: prestissimo, flex
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: composer install --no-interaction --no-suggest

            - name: Run the unit tests
              run: vendor/bin/phpunit --colors=always

    nightly:
        name: PHP 8.4
        runs-on: ubuntu-latest
        if: github.event_name != 'push'
        continue-on-error: true
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, pcre, pdo_mysql, zlib
                  tools: prestissimo, flex
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: composer install --ignore-platform-req=php+ --no-interaction --no-suggest

            - name: Run the unit tests
              run: vendor/bin/phpunit --colors=always

    prefer-lowest:
        name: Prefer Lowest
        runs-on: ubuntu-latest
        if: github.event_name != 'push'
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, pcre, pdo_mysql, zlib
                  tools: prestissimo, flex
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: composer update --prefer-lowest --prefer-stable --no-interaction --no-suggest

            - name: Run the unit tests
              run: vendor/bin/phpunit --colors=always
